name: bc-ev-stations
channels:
  - defaults
  - conda-forge
dependencies:
  - geopandas
  - statsmodels
  - shapely
  - ipywidgets
  - requests
  - seaborn
  - jupyterlab
  - nb_conda_kernels
  - folium
  - jinja2==3.0.3
